---
- name: install ntp
  apt: pkg={{ item }} state=latest
  with_items:
    - ntp
  when: ansible_os_family == "Debian"

- name: update timezone
  copy: content={{ timezone }}
        dest=/etc/timezone
        backup=yes
  notify:
    - update timezone
