- hosts: all
  sudo: True
  user: travis
  vars:
    server_name: www.spider
    timezone: Asia/Tokyo
    lang: ja_JP.UTF-8
  roles:
    - common
    - python
    - ntp
    - role: nginx
      nginx_sites: none
    - redis
    - mongod
