- name: install common packages debian/ubuntu
  apt: pkg={{ item }} state=latest
  with_items:
    - python
    - python-dev
    - python-setuptools
    - python-virtualenv
    - python-pip
  when: ansible_os_family == "Debian"

- name: upgrade pip
  pip: name=pip extra_args=--upgrade

- name: install ansible
  pip: name=ansible
