---
- name: update apt package cache
  apt: update_cache=yes
  when: ansible_os_family == "Debian"

- name: install common packages debian/ubuntu
  apt: pkg={{ item }} state=latest
  with_items:
    - build-essential
    - vim
    - git-core
    - supervisor
    - libxslt1-dev
    - libxml2-dev
    - zlib1g-dev
    - libffi-dev
    - libssl-dev

- name: install the locales package
  apt: pkg=locales state=present
  when: ansible_os_family == "Debian"

- name: update locale lang
  locale_gen: name={{ lang }} state=present
  when: ansible_os_family == "Debian"
